-- Migration script for Form Notifications
CREATE TABLE IF NOT EXISTS form_notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    form_id INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    is_enabled TINYINT(1) DEFAULT 0,
    to_recipients VARCHAR(255) NOT NULL,
    cc_recipients VARCHAR(255) NULL,
    bcc_recipients VARCHAR(255) NULL,
    reply_to VARCHAR(150) NULL,
    from_name VARCHAR(100) NULL,
    from_email VARCHAR(150) NULL,
    subject_template VARCHAR(255) NOT NULL,
    body_template TEXT NOT NULL,
    body_format VARCHAR(20) DEFAULT 'html',
    attach_uploads TINYINT(1) DEFAULT 0,
    attach_submission_pdf TINYINT(1) DEFAULT 0,
    include_all_fields TINYINT(1) DEFAULT 0,
    conditional_logic_json TEXT NULL,
    sort_order INT DEFAULT 0,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    trigger_event VARCHAR(50) DEFAULT 'submit',
    recipient_type VARCHAR(50) DEFAULT 'fixed',
    recipient_role_id INT(11) DEFAULT NULL,
    recipient_dept_id INT(11) DEFAULT NULL,
    FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS form_notification_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    notification_id INT NULL,
    form_id INT NOT NULL,
    submission_id INT NULL,
    job_id INT NULL,
    recipient_summary VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    attempts INT DEFAULT 0,
    provider_response TEXT NULL,
    error_message TEXT NULL,
    sent_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    response_message TEXT DEFAULT NULL,
    FOREIGN KEY (notification_id) REFERENCES form_notifications(id) ON DELETE SET NULL,
    FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE,
    FOREIGN KEY (submission_id) REFERENCES form_submissions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
